name: hexrdgui-package
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - coloredlogs
  - conda
  - cmake
  # FIXME: we have some issues with conda-build 25 and greater
  # We should figure out these issues and remove this pin after
  - conda-build<25
  - conda-pack
  - click
  - conda-libmamba-solver
